
// Lockstatus constants
export const LOCK_SOCKET_AUTHENTICATE = 'LOCK_SOCKET_AUTHENTICATE';
export const LOCK_ACTIVATE_BTN = 'LOCK_ACTIVATE_BTN';
export const LOCK_NEW_LOG_DATA = 'LOCK_NEW_LOG_DATA';
export const LOCK_STATE_UPDATE = 'LOCK_STATE_UPDATE';
export const LOCK_FORCE_OPEN = 'LOCK_FORCE_OPEN';
export const LOCK_FORCE_CLOSE = 'LOCK_FORCE_CLOSE';
export const LOCK_SET_AUTH_STATUS = 'LOCK_SET_AUTH_STATUS';
export const LOCK_SET_SOCKET_STATUS = 'LOCK_SET_SOCKET_STATUS';
